#!/bin/bash

. /etc/init.d/functions         # source function library
. /etc/profile.d/padfinder.sh   # environment

daemon=padfinder-commute
workdir="/code/padfinder/padfinder"
prog="$workdir/commute.sh"
config_dir=/etc/padfinder
lockfile=/var/lock/subsys/$daemon
pid_file="/var/run/${daemon}.pid"


start() {
    echo -n $"Starting $daemon ($prog): "
    cd $workdir
    nohup $prog $config_dir < /dev/null > /var/log/${daemon}.log 2>&1 &
    echo $! > "$pid_file"
    retval=$?
    echo

    # If all is well touch the lock file
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Shutting down $daemon: "
    killproc -p $pid_file
    retval=$?
    echo

    # If all is well remove the pidfile and the lockfile
    [ $retval -eq 0 ] && rm -f $pid_file && rm -f $lockfile
    return $retval
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p $pid_file $daemon
        ;;
  restart)
        stop
        start
        ;;
   *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
